version: '3.8'

services:
  backend:
    build:
      context: ./excel-processor
      dockerfile: Dockerfile
    # 🔥 THE FIX 1: Smiya jdida unique bach n-khliw App 1 trankil
    container_name: kyntus_os_backend_v2
    restart: unless-stopped
    ports:
      # Optionnel: y9der Omar yt-testi API nichan f 8085
      - "8085:8081" 
    deploy:
      resources:
        limits:
          memory: 1G 
    networks:
      - kyntus-v2-network

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
      # 🔥 THE FIX 2: L'Injection darouriya bach Client (Browser) y3ref l'Backend
      args:
        - NEXT_PUBLIC_API_URL=http://10.10.10.50:8085
    # 🔥 THE FIX 1: Smiya jdida unique l'Frontend
    container_name: kyntus_os_frontend_v2
    ports:
      # L'Host ghadi ychouf 3005
      - "3005:3000"
    environment:
      # DNS dyal Docker kay-traduj 'backend' l'IP interne dyal Spring Boot (pour SSR)
      - BACKEND_URL=http://backend:8081
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - kyntus-v2-network

# 🔥 THE FIX 3: Réseau jdid m3zoul (Isolated) bach App 2 t-hder m3a b3diyat'ha b slama
networks:
  kyntus-v2-network:
    driver: bridge