version: '3.8'

services:
  backend:
    build:
      context: ./excel-processor
      dockerfile: Dockerfile
    container_name: kyntus_backend
    restart: unless-stopped
    ports:
      # L'Backend m7loul l'Serveur f 8085
      - "8085:8081" 
    deploy:
      resources:
        limits:
          memory: 1G 

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
      # 🔥 THE FIX: Injection dyal l'IP d'l'VPS f waqt l'Build bach Chrome y3ref tri9
      args:
        # Bddel 10.10.10.50 b l'IP d'charika ila kan beddelouh, w l'Port houwa 8085
        - NEXT_PUBLIC_API_URL=http://10.10.10.50:8085
    container_name: kyntus_frontend
    ports:
      - "3005:3000"
    environment:
      # Ila 3ndk chi code Server-Side (getServerSideProps/API Routes) f Next.js, hadi ghat-nff3o
      - BACKEND_URL=http://backend:8081
      - NEXT_PUBLIC_API_URL=http://10.10.10.50:8085
    depends_on:
      - backend
    restart: unless-stopped