spring.application.name=excel-processor
server.port=8081

# L'autorisation dyal les fichiers kbar (Risk Mitigation)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB